version: '3'
services:
  wstunnel-server:
    # latest tag => v5.0
    image: javidi/wstunnel:latest
    container_name: ws-srv
    restart: unless-stopped
    network_mode: host
    environment:
      #local
      - COMMAND=/usr/local/bin/wstunnel -v --server ws://0.0.0.0:33344 --restrictTo=127.0.0.1:51820
      #external
      #- COMMAND=/usr/local/bin/wstunnel -v --server ws://0.0.0.0:33344